language: julia
sudo: true
os:
    - linux
julia:
    - 0.7
    - nightly
addons:
  apt:
    packages:
      - python3-pip
before_install:
    - sudo apt-get update
    - sudo pip install --upgrade visualdl
script:
    - julia -e 'Pkg.build("VisualDL"); Pkg.test("VisualDL"; coverage=true)'
after_success:
    - julia -e 'Pkg.add("Documenter"); include(joinpath("docs", "make.jl"))'
notifications:
    email: false